configure_machine: &configure_machine
  machine: true
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

version: 2
jobs:
    regression_centoscore_QA:
      <<: *configure_machine
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
    run_feature_tests:
      <<: *configure_machine
      steps:
        - checkout
        - attach_workspace:
            at: ~/TEST
        - add_ssh_keys:
            fingerprints:
              - "31:38:1c:d3:5f:26:79:b0:8f:e6:33:ed:31:7d:19:70"
 
        - run:
            name: Clone Comply QAF
            command: >-
              GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_fingerprint'
              git clone git@github.com:BhimaRanganath/TestRepo.git ~/TEST 
workflows:
    version: 2
    regression:
        jobs:
            - regression_centoscore_QA
            - run_feature_tests
