configure_machine: &configure_machine
  machine: true
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
checkout_all: &checkout_all
  checkout:
    name: Checkout With all Submodules and Tags
    command: |
      git fetch --depth=2147483647
      git fetch --tags

version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
checkout_repo:
    <<: *configure_machine
    steps:
      - *checkout_all
      - run:
          name: Verifying commits follow semantic versioning
          command: 'echo "hello world"'
workflows:
  version: 2
  build_branch:
    jobs:
      - checkout_repo
