configure_machine: &configure_machine
  machine: true
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

version: 2
jobs:
    regression_centoscore_QA:
      <<: *configure_machine
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
    run_feature_tests:
      <<: *configure_machine
      steps:
        - checkout
        - attach_workspace:
            at: ~/TEST
        - add_ssh_keys:
            fingerprints:
              - "4b:87:63:47:76:94:d8:e7:71:56:34:1e:2d:d7:30:3a"
 
        - run:
            name: Clone Comply QAF
            command: >-
              GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
              git clone git@github.com:dequelabs/qa_comply_daf.git ~/TEST 
workflows:
    version: 2
    regression:
        jobs:
            - regression_centoscore_QA
            - run_feature_tests
