configure_machine: &configure_machine
  machine: true
  environment:
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx1024m -XX:+HeapDumpOnOutOfMemoryError"'
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

version: 2
jobs:
    regression_centoscore_QA:
       <<: *configure_machine
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
    run_feature_tests:
        docker:
      # specify the version you desire here
      # - image: circleci/openjdk:8-jdk
            - image: circleci/openjdk:8-jdk-browsers
        steps:
          - checkout
          - attach_workspace:
              at: ~/TEST
          - add_ssh_keys:
              fingerprints:
                - "1a:8c:49:ef:cc:9c:ad:f3:ec:00:fd:0c:9e:47:a2:8b"
          - run:
              name: Clone Comply QAF
              command: >-
                GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                git clone git@github.com:BhimaRanganath/TestRepo.git ~/TEST 
workflows:
    version: 2
    regression:
        jobs:
            - regression_centoscore_QA
            - run_feature_tests
