version: 2
jobs:
    regression_centoscore_QA:
        docker:
      # specify the version you desire here
      # - image: circleci/openjdk:8-jdk
            - image: circleci/openjdk:8-jdk-browsers
        steps:
            - checkout # check out the code in the project directory
            - run: echo "hello world" # run the `echo` command
    run_feature_tests:
        docker:
      # specify the version you desire here
      # - image: circleci/openjdk:8-jdk
            - image: circleci/openjdk:8-jdk-browsers
        steps:
          - checkout
          - attach_workspace:
              at: ~/TEST
          - add_ssh_keys:
              fingerprints:
                - "8b:10:7c:49:05:c3:a0:95:ba:7b:38:29:bc:47:6f:7d"
          - run:
              name: Clone Comply QAF
              command: >-
                GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_fingerprint'
                git clone git@github.com:dequelabs/qa_comply_daf.git ~/TEST    
workflows:
    version: 2
    regression:
        jobs:
            - regression_centoscore_QA
            - run_feature_tests
