version: 1
update_configs:
  # Keep gradle up to date daily
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*:*"
          update_type: "all"
    commit_message:
      prefix: "chore"
