version: 1
update_configs:
  # Keep gradle up to date daily
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*:*"
          # Supported dependency types:
          # - "development"
          # - "production"
          # - "all"
          update_type: "semver:minor"

    commit_message:
      prefix: "chore"
