version: 1
update_configs:
  # Keep gradle up to date daily
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_name: "*:*"
          update_type: "semver:patch"
      - match:
          # Wildcards match unlimited arbitrary characters (or none)
          dependency_name: "rspec*"
    commit_message:
      prefix: "chore"
